### ISSUE TITLE
Array of Zodiac Objects

### ISSUE THREAD

**Issue by LeeGee64** [LeeGee64/-100DevsZodiacDetermination#3]
In the server doc create an Array that stores objects containing the Zodiac name alongside the link to the proper image.

**Comment by CodingComrade** [comment]
I'll take this on

**Comment by shaylalewis** [comment]
I have an idea for this if it won't be too much extra work. Instead of having the descriptions on the images like I originally thought, would it be okay to add a description of each sign to the object? We can create another issue so someone can get those to be added to the object. Also, is this the proper place for suggestions?

**Comment by LeeGee64** [comment]
Adding the description to the object is a great idea! 

I think someone is creating a slack for this project where the chat can be a bit more fluid
